### PR TITLE
Check the ovs-rally output

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang kangh@us.ibm.com

### CODE REVIEW

**Comment by huikang** [comment]
Address #69 and #86

**Comment by huikang** [comment]
I know this is not perfect; but it is a quick fix.

**Comment by huikang** [comment]
@mestery this PR is ready for review; the failing is expected.

**Comment by mestery** [comment]
@huikang When you say the failure is expected, does this mean once we merge this all of our CI jobs will fail because they are already failing and we're not noticing?

**Comment by huikang** [comment]
@mestery Your understanding is correct. The failing is caused by some earlier commit. I will find out and fix it today.

**Comment by huikang** [comment]
@mestery lets leave the PR un-merged until I fix the rally_ovs issue.

**Comment by huikang** [comment]
@mestery since rally_ovs has been fixed for CI job, this PR is ready for review now. Thanks.

**Pull request merged**
