### PR TITLE
Override the version of OVS to test

### PR DESCRIPTION
**Pull request by mestery**
This allows for the version of OVS to be tested. One piece is missing
which I need insight on: How to override the version of OVS cloned
into the Dockerfile for the built containers.

Signed-off-by: Kyle Mestery mestery@mestery.com

### CODE REVIEW

**Comment by mestery** [comment]
I need feedback on how to allow the OVS cloned in the Docker containers to be configured as well. This is needed to hook into a CI system like zuul which will tell the software what repository and branch to test.

**Comment by mestery** [comment]
This is now ready for review and does allow for overriding the repository and branch of OVS being tested. This will be used as we integrate ovn-scale-test into the CI/CD systems.

**Comment by huikang** [comment]
Nice! Could you add some instructions about how to build the images? Thanks.

**Comment by mestery** [comment]
@huikang By default it works as it did before. See the changes in my ovn-scale-cicd repo (which I will merge into this one) for how it's used.

**Comment by huikang** [comment]
@mestery understood now. waiting for the updated PR with script from ovn-scale-cicd.

**Comment by mestery** [comment]
@huikang Actually this one can merge first, I'll submit the collapse of ovn-scale-cicd into ovn-scale-test tomorrow. But I'm fine waiting as well.

**Comment by huikang** [comment]
Tested and it works. Thanks!

**Pull request merged**
