### PR TITLE
Use ansible to create deploy user

### PR DESCRIPTION
**Pull request by huikang**
Ansible provides more flexibility in creating user

Signed-off-by: Hui Kang kangh@us.ibm.com

### CODE REVIEW

**Comment by huikang** [comment]
@mestery FYI

**Comment by huikang** [comment]
@l8huang could you help to review this PR? Thanks.

**Comment by mestery** [comment]
This LGTM and will be much more flexible, thanks Hui!

**Comment by mestery** [comment]
Without this change, the current repository does not work. With this change, it does work. So I think this should be merged.

**Comment by huikang** [comment]
@mestery thanks for testing the PR. To be more specific, this PR fixes the deployment in an all-in-one environment.

@l8huang @hzhou8 could you help review this PR? Thanks.

**Pull request merged**
