### PR TITLE
Stop hardcoding the ubuntu user

### PR DESCRIPTION
**Pull request by mestery**
Determine what user to run as dynamically.

Signed-off-by: Kyle Mestery mestery@mestery.com

### CODE REVIEW

**Comment by huikang** [comment]
Does that mean any user can run this CI script and launch docker container, as long as the user is in the sudo list?

**Comment by mestery** [comment]
@huikang Yes, what was in there assumed the user was "ubuntu", which was not working on our internal CI.

**Comment by huikang** [comment]
gotcha.

**Comment by huikang** [comment]
If the change is tested in internal CI and success, I would like to merge it.

**Comment by mestery** [comment]
@huikang It is tested and should be mergable!

**Pull request merged**
